class Common {
  static String PATH_IMG = "assets/images/";
  static const String NEXT = "Tiếp";
  static const String DONE = "Xong";
}

class Category {
  static const List<String> QUESTION_NAME = [
    "Hạng mục nào mô tả chính xác nhất về NAME_OF_PAGE ?",
    "Nhờ hạng mục, mọi người sẽ tìm thấy Trang này trong kết quả tìm kiếm. Bạn có thể thêm đến 3 hạng mục",
  ];
  static const String PLACEHOLDER_CATEGORY = "Tìm kiếm hạng mục";
  static const String TITLE = "Hạng mục phổ biến";
  static const List<String> POPULAR_CATEGORY = [
    "Blog cá nhân",
    "Sản phẩm/ Dịch vụ",
    "Nghệ thuật",
    "Nhạc sỹ/ Ban nhạc"
  ];
  static const String WARNING_MESSAGE = "Bạn đã chọn hạng mục này !!";
  static const List<String> listSelection = [
    "Sản phẩm/ Dịch vụ",
    "Dịch vụ kinh doanh",
    "Người sáng tạo nội dung số",
    "Giáo dục",
    "Trung tâm kinh doanh",
    "Y tế và Sức khỏe",
    "Cửa hàng sửa chữa ô tô",
    "Blog cá nhận",
    "Giải trí",
    "Nghệ thuật",
    "Nhạc sỹ/ Ban nhạc",
    "Album",
    "Trung tâm điều trị nghiện rượu",
    "Dị ứng",
    "Dịch vụ Y tế Thay thế & Toàn diện",
    "Nhiếp ảnh gia nghiệp dư",
    "Liên đoàn thể thao nghiệp dư",
    "Đội thể thao nghiệp dư",
    "Nhà hàng Mỹ",
    "Nhà hàng Andhra",
    "Bác sĩ gây mê",
    "Giáo hội Anh giáo",
    "Nhà hàng An Huy",
    "Dịch vụ cứu hộ động vật",
    "Nhà hàng Abruzzo",
    "Trại học thuật",
    "Phụ kiện",
    "Kế toán viên",
    "Nhà hàng Acehnese",
    "Diễn viên nam",
    "Bác sĩ châm cứu",
    "Trung tâm tài nguyên về chất gây nghiện",
    "Dịch vụ cai nghiện",
    "Trung tâm Điều trị Nghiện",
    "Dịch vụ nhận con nuôi",
    "Dịch vụ giải trí dành cho người lớn",
    "Công ty hàng không vũ trụ",
    "Nhà hàng Afghanistan",
    "Nhà thờ Giám lý Giám lý Châu Phi",
    "Nhà hàng Châu Phi",
    "Trung tâm Tài nguyên AIDS",
    "Nhà sản xuất máy bay",
    "Công ty hàng không",
    "Dịch vụ ngành hàng không",
    "Phi trường",
    "Cổng sân bay",
    "Phòng chờ sân bay",
    "Dịch vụ đưa đón sân bay",
    "Nhà ga sân bay",
    "Nơi trú ẩn động vật",
    "Xưởng phim hoạt hình",
    "Cửa hàng đồ cổ",
    "Nhà hàng Aosta",
    "Căn hộ & Tòa nhà chung cư",
    "Giáo hội Tông đồ",
    "Trang ứng dụng",
    "Trang phục & Quần áo",
    "Nhà phân phối quần áo",
    "Nhà sản xuất thiết bị",
    "Dịch vụ sửa chữa thiết bị",
    "Cửa hàng thiết bị",
    "Thiết bị gia dụng",
    "Cửa hàng thú cưng thủy sinh",
    "Nhà hàng Ả Rập",
    "Vườn ươm",
    "Dịch vụ khảo cổ học",
    "Dãy bắn cung",
    "Cửa hàng bắn cung",
    "Nhà thiết kế kiến ​​trúc",
    "Đại lý du lịch kiến ​​trúc",
    "Nhà hàng Argentina",
    "Lực lượng vũ trang",
    "Nhà hàng Armenia",
    "Dịch vụ trị liệu bằng hương thơm",
    "Mỹ thuật",
    "Dịch vụ phục hồi nghệ thuật",
    "Trường nghệ thuật",
    "Cơ quan lưu diễn nghệ thuật",
    "Bài báo",
    "Họa sĩ",
    "Cửa hàng thủ công & nghệ thuật",
    "Trang web Nghệ thuật & Nhân văn",
    "Nhà hàng món kết hợp châu Á",
    "Nhà hàng Châu Á",
    "Sự lắp ráp của Chúa",
    "Nhà chiêm tinh học",
    "Nhà chiêm tinh & Nhà ngoại cảm",
    "Lực sĩ",
    "Công viên giải trí ATV",
    "ATV cho thuê",
    "Nhà đấu giá",
    "Cửa hàng thiết bị nghe nhìn",
    "Nhà thính học",
    "Nhà hàng Úc",
    "Nhà hàng Áo",
    "Tác giả",
    "Dịch vụ chi tiết tự động",
    "Máy giao dịch tự động (ATM)",
    "Dịch vụ tự động hóa",
    "Cửa hàng cơ thể ô tô",
    "Tư vấn ô tô",
    "Cửa hàng tùy chỉnh ô tô",
    "Dịch vụ kính ô tô",
    "Dịch vụ cho thuê ô tô",
    "Nhà sản xuất ô tô",
    "Cửa hàng phụ tùng ô tô",
    "Trung tâm đăng kiểm ô tô",
    "Cửa hàng sửa chữa ô tô",
    "Dịch vụ phục hồi ô tô",
    "Dịch vụ ô tô",
    "Dịch vụ vận chuyển ô tô",
    "Cơ sở lưu trữ ô tô",
    "Cửa hàng ô tô",
    "Dịch vụ đánh bóng bánh xe ô tô",
    "Dịch vụ pha màu cửa sổ ô tô",
    "Trạm sửa chữa hàng không",
    "Trường hàng không",
    "Cửa hàng điện tử",
    "Nhà hàng Awadhi",
    "Nhà cung cấp mái hiên",
    "Nhà hàng Azerbaijan",
    "Cửa hàng quần áo trẻ em & trẻ em",
    "Hàng trẻ em / Hàng trẻ em",
    "Người trông trẻ",
    "Nhà hàng Baden",
    "Sân cầu lông",
    "Cửa hàng bánh mì tròn",
    "Công ty Túi xách & Hành lý",
    "Cửa hàng túi xách & hành lý",
    "Túi xách / Hành lý",
    "Bảo lãnh tại ngoại",
    "Cửa hàng bánh mì",
    "Nhà hàng Bali",
    "Balloonport",
    "Phòng khiêu vũ",
    "Ban nhạc",
    "Ngân hàng",
    "Thiết bị & Dịch vụ Ngân hàng",
    "Luật sư phá sản",
    "Nhà thờ Baptist",
    "Quán ba",
    "Bar & Grill"
  ];
}
